/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

module counter4sync(clk, rst, en, count);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input en;
  wire en;
  output [3:0] count;
  wire [3:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [3:0] _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  INV_X1 _15_ (
    .A(_11_[0]),
    .ZN(_04_)
  );
  NOR2_X1 _16_ (
    .A1(en),
    .A2(count[0]),
    .ZN(_05_)
  );
  AOI211_X1 _17_ (
    .A(rst),
    .B(_05_),
    .C1(en),
    .C2(_04_),
    .ZN(_00_)
  );
  AND3_X1 _18_ (
    .A1(en),
    .A2(count[1]),
    .A3(count[0]),
    .ZN(_06_)
  );
  AOI21_X1 _19_ (
    .A(count[1]),
    .B1(count[0]),
    .B2(en),
    .ZN(_07_)
  );
  NOR3_X1 _20_ (
    .A1(rst),
    .A2(_06_),
    .A3(_07_),
    .ZN(_01_)
  );
  AND4_X1 _21_ (
    .A1(count[2]),
    .A2(en),
    .A3(count[1]),
    .A4(count[0]),
    .ZN(_08_)
  );
  XNOR2_X1 _22_ (
    .A(count[3]),
    .B(_08_),
    .ZN(_09_)
  );
  NOR2_X1 _23_ (
    .A1(rst),
    .A2(_09_),
    .ZN(_02_)
  );
  NOR2_X1 _24_ (
    .A1(count[2]),
    .A2(_06_),
    .ZN(_10_)
  );
  NOR3_X1 _25_ (
    .A1(rst),
    .A2(_08_),
    .A3(_10_),
    .ZN(_03_)
  );
  DFF_X1 _26_ (
    .CK(clk),
    .D(_00_),
    .Q(count[0]),
    .QN(_11_[0])
  );
  DFF_X1 _27_ (
    .CK(clk),
    .D(_01_),
    .Q(count[1]),
    .QN(_14_)
  );
  DFF_X1 _28_ (
    .CK(clk),
    .D(_03_),
    .Q(count[2]),
    .QN(_12_)
  );
  DFF_X1 _29_ (
    .CK(clk),
    .D(_02_),
    .Q(count[3]),
    .QN(_13_)
  );
  assign _11_[3:1] = count[3:1];
endmodule
