/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

module counter8(clk, rst_n, en, count);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input en;
  wire en;
  output [7:0] count;
  wire [7:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire [7:0] _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  INV_X1 _24_ (
    .A(count[6]),
    .ZN(_08_)
  );
  NAND2_X1 _25_ (
    .A1(count[0]),
    .A2(en),
    .ZN(_09_)
  );
  NAND3_X1 _26_ (
    .A1(count[0]),
    .A2(count[1]),
    .A3(en),
    .ZN(_10_)
  );
  AND4_X1 _27_ (
    .A1(count[0]),
    .A2(count[1]),
    .A3(count[2]),
    .A4(en),
    .ZN(_11_)
  );
  NAND2_X1 _28_ (
    .A1(count[3]),
    .A2(_11_),
    .ZN(_12_)
  );
  NAND3_X1 _29_ (
    .A1(count[3]),
    .A2(count[4]),
    .A3(_11_),
    .ZN(_13_)
  );
  NAND4_X1 _30_ (
    .A1(count[3]),
    .A2(count[4]),
    .A3(count[5]),
    .A4(_11_),
    .ZN(_14_)
  );
  NOR2_X1 _31_ (
    .A1(_08_),
    .A2(_14_),
    .ZN(_15_)
  );
  XNOR2_X1 _32_ (
    .A(count[6]),
    .B(_14_),
    .ZN(_00_)
  );
  XNOR2_X1 _33_ (
    .A(count[5]),
    .B(_13_),
    .ZN(_01_)
  );
  XNOR2_X1 _34_ (
    .A(count[4]),
    .B(_12_),
    .ZN(_02_)
  );
  XOR2_X1 _35_ (
    .A(count[3]),
    .B(_11_),
    .Z(_03_)
  );
  XNOR2_X1 _36_ (
    .A(count[2]),
    .B(_10_),
    .ZN(_04_)
  );
  XNOR2_X1 _37_ (
    .A(count[1]),
    .B(_09_),
    .ZN(_05_)
  );
  MUX2_X1 _38_ (
    .A(count[0]),
    .B(_16_[0]),
    .S(en),
    .Z(_06_)
  );
  XOR2_X1 _39_ (
    .A(count[7]),
    .B(_15_),
    .Z(_07_)
  );
  DFFR_X1 _40_ (
    .CK(clk),
    .D(_06_),
    .Q(count[0]),
    .QN(_16_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _41_ (
    .CK(clk),
    .D(_05_),
    .Q(count[1]),
    .QN(_18_),
    .RN(rst_n)
  );
  DFFR_X1 _42_ (
    .CK(clk),
    .D(_04_),
    .Q(count[2]),
    .QN(_19_),
    .RN(rst_n)
  );
  DFFR_X1 _43_ (
    .CK(clk),
    .D(_03_),
    .Q(count[3]),
    .QN(_20_),
    .RN(rst_n)
  );
  DFFR_X1 _44_ (
    .CK(clk),
    .D(_02_),
    .Q(count[4]),
    .QN(_21_),
    .RN(rst_n)
  );
  DFFR_X1 _45_ (
    .CK(clk),
    .D(_01_),
    .Q(count[5]),
    .QN(_22_),
    .RN(rst_n)
  );
  DFFR_X1 _46_ (
    .CK(clk),
    .D(_00_),
    .Q(count[6]),
    .QN(_23_),
    .RN(rst_n)
  );
  DFFR_X1 _47_ (
    .CK(clk),
    .D(_07_),
    .Q(count[7]),
    .QN(_17_),
    .RN(rst_n)
  );
  assign _16_[7:1] = count[7:1];
endmodule
